exclude: "^docs/|/migrations/|^tests/"
default_stages: [commit]

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.260"
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/python-poetry/poetry
    rev: '1.5.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
        stages: [manual]  # Only run manually, not in CI
      - id: poetry-export
        args: ["-o", "requirements.txt", "--with=dev", "--without-hashes"]
        stages: [manual]  # Only run manually, not in CI


# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: [poetry-lock, poetry-export]  # Skip file-modifying hooks in CI
  submodules: false
