name: Update Changelog

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-changelog:
    name: Update CHANGELOG.md
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.event.release.tag_name }} [skip ci]'
          file_pattern: CHANGELOG.md
